spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dart_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root  

  jpa:
    hibernate:
      ddl-auto: none  
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # DART API 설정
dart:
  api-key: 233c213071c6dc2bfeb088ac7d788ad8aaaacd81